openapi: 3.1.0
info:
  version: '1.0'
  title: Nigeria Locale
  summary: 'It''s an API for geographic data of places in Nigeria. It is used to get or search for states, local government areas and regions. '
  description: |
    Nigeria Locale is a developer tool for anyone who needs to know Nigeria, geographically at least. Nigeria Locale’s API shows you all of Nigeria’s regions, states, and local government areas(LGAs). Locale is looking to be a very useful tool for the thousands of businesses building for Nigeria’s 200M+ population size.
  contact:
    email: emmanueltopea@gmail.com
    name: Emmanuel Oloyede
    url: 'https://github.com/techemmy/nigeria-locale'
  license:
    url: 'https://www.mit.edu/~amini/LICENSE.md'
    name: MIT License
paths:
  /auth/signup:
    post:
      tags:
        - auth
      summary: User Signup
      description: Create a new account on this endpoint and generate API key for user
      operationId: post-auth-signup
      requestBody:
        description: The new user data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
            examples:
              Example 1:
                value:
                  username: janedoe
                  email: jane@doe.com
                  password: janedoe
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      userAPIKey:
                        type: string
                      Note:
                        type: string
                      loginToken:
                        type: string
              examples:
                Example 1:
                  value:
                    success: true
                    message: signup successful
                    data:
                      userAPIKey: $2b$10$8BxPpsNoRc4XMbfqYEApJO2x/LC9asjp9ClEToQFZ75CL66EDIcGO
                      Note: Copy your key and save it. We won't show it to you again
                      loginToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0OTM5MTNiYzZlODFiNDNhOTJkZjY3ZiIsInVzZXJuYW1lIjoiamFuZWRvZSIsImlhdCI6MTY4NzM5MjU3NCwiZXhwIjoxNjg3OTk3Mzc0fQ.cRHkZrmEcXknG-pL06HbzAnruTHfA_mxMvWfeHx3iOE
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  errorCode:
                    type: integer
                  data:
                    type: object
      security: []
  /auth/login:
    post:
      tags:
        - auth
      summary: User Login
      description: Log in to get JWT token for generating a new API key
      operationId: post-auth-login
      requestBody:
        description: The user's username and password
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
            examples:
              Example 1:
                value:
                  username: janedoe
                  password: janedoe
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      loginToken:
                        type: string
              examples:
                Example 1:
                  value:
                    success: true
                    message: login succesful
                    data:
                      loginToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0OTM5MTNiYzZlODFiNDNhOTJkZjY3ZiIsInVzZXJuYW1lIjoiamFuZWRvZSIsImlhdCI6MTY4NzM5MjgwNiwiZXhwIjoxNjg3OTk3NjA2fQ.DuqjYB-x0jLe2CwN6ZyDZBKe9MIESdGjMUxZ2GIjKNI
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  errorCode:
                    type: integer
                  data:
                    type: object
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                  errorCode:
                    type: integer
      security: []
  /api/v1/get-new-key:
    get:
      tags:
        - auth
      summary: Regenerate API Key
      description: Regenerate a new API key
      operationId: get-api-v1-get-new-key
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      APIKey:
                        type: string
                      Note:
                        type: string
              examples:
                Example 1:
                  value:
                    success: true
                    message: New Key Generated!
                    data:
                      APIKey: $2b$10$fYxI13LEA4gh91ipJFbbo.5SIwZUJLS/y0LmJxEwpxPdkBr0mZdvq
                      Note: Copy your key and save it. We won't show it to you again
        '401':
          description: Unauthorized
          content:
            text/plain:
              schema:
                type: string
                examples:
                  - Unauthorized
              examples:
                default:
                  value: Unauthorized
                Example 1:
                  value: Unauthorized
      security:
        - LoginToken: []
  /api/v1/regions:
    get:
      tags:
        - location
      summary: Get Regions
      description: Gets a list of regions in Nigeria
      operationId: get-api-v1-regions
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      size:
                        type: integer
                      result:
                        type: array
                        items:
                          type: string
              examples:
                Example 1:
                  value:
                    success: true
                    message: List of Regions
                    data:
                      size: 6
                      result:
                        - South East
                        - North East
                        - South South
                        - North Central
                        - South West
                        - North West
        '401':
          $ref: '#/components/responses/401-Response-for-API'
      security:
        - APIKey: []
  /api/v1/states:
    get:
      tags:
        - location
      summary: Get States
      description: Gets a list of states in Nigeria
      operationId: get-api-v1-states
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      size:
                        type: integer
                      result:
                        type: array
                        items:
                          type: string
              examples:
                Example 1:
                  value:
                    success: true
                    message: List of States
                    data:
                      size: 37
                      result:
                        - Abia
                        - Adamawa
                        - Akwa Ibom
                        - Anambra
                        - Bauchi
                        - Benue
                        - Borno
                        - Bayelsa
                        - Cross River
                        - Delta
                        - Ebonyi
                        - Edo
                        - Ekiti
                        - Enugu
                        - Federal Capital Territory
                        - Gombe
                        - Imo
                        - Jigawa
                        - Kebbi
                        - Kaduna
                        - Kano
                        - Kogi
                        - Katsina
                        - Kwara
                        - Lagos
                        - Nassarawa
                        - Niger
                        - Ogun
                        - Ondo
                        - Osun
                        - Oyo
                        - Plateau
                        - Rivers
                        - Sokoto
                        - Taraba
                        - Yobe
                        - Zamfara
        '401':
          $ref: '#/components/responses/401-Response-for-API'
      security:
        - APIKey: []
  /api/v1/LGAs:
    get:
      tags:
        - location
      summary: Get Local Government Areas (LGA)
      description: Gets a list of the local government areas (LGA) in Nigeria
      operationId: get-api-v1-LGAs
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      size:
                        type: integer
                      result:
                        type: array
                        items:
                          type: string
              examples:
                Example 1:
                  value:
                    success: true
                    message: List of Local Government Areas (LGAs)
                    data:
                      size: 846
                      result:
                        - Aba North
                        - Aba South
                        - Arochukwu
                        - Bende
                        - Isuikwuato
                        - Osisioma-Ngwa
                        - Obioma-Ngwa
                        - Ohafia
                        - Ikwuano
                        - Umu-Nneochi
                        - Isiala Ngwa South
                        - Isiala Ngwa North
                        - Ugwunagbo
                        - Ukwa West
                        - Ukwa East
                        - Umuahia South
                        - Umuahia North
                        - Demsa
                        - Fufore
                        - Ganye
                        - Girei
                        - Gombi
                        - Jada
                        - Yola North
                        - Lamurde
                        - Madagali
                        - Maiha
                        - Mayo-Belwa
                        - Michika
                        - Mubi South
                        - Mubi North
                        - Numna
                        - Shelleng
                        - Song
                        - Toungo
                        - Jimeta
                        - Yola South
                        - Hung
                        - Abak
                        - Eastern Obolo
                        - Eket
                        - Essien Udim
                        - Etimekpo
                        - Etinan
                        - Ibeno
                        - Ibesikpo Asutan
                        - Ibiono Ibom
                        - Ika
                        - Ikono
                        - Ikot Abasi
                        - Ikot Ekpene
                        - Ini
                        - Itu
                        - Mbo
                        - Mkpat Enin
                        - Nsit Ibom
                        - Nsit Ubium
                        - Obot Akara
                        - Okobo
                        - Onna
                        - Orukanam
                        - Oron
                        - Udung Uko
                        - Ukanafun
                        - Esit Eket
                        - Uruan
                        - Urue Offoung
                        - Oruko Ete
                        - Uyo
                        - Aguata
                        - Akwa North
                        - Anambra
                        - Anambra-West
                        - Anaocha
                        - Awka-North
                        - Awka-South
                        - Ayamelum
                        - Dunukofia
                        - Ekwusigo
                        - Idemili-North
                        - Idemili-South
                        - Ihiala
                        - Imo
                        - Nibo
                        - Njikoka
                        - Nnewi-North
                        - Nnewi-South
                        - Ogbaru
                        - Olumba
                        - Onitsha-North
                        - Onitsha-South
                        - Orumba-North
                        - Orumba-South
                        - Oti
                        - Otu-Ocha
                        - Ubuluizor Ihiala
                        - Uyi
                        - Alkaleri
                        - Bauchi
                        - Bogoro
                        - Damban
                        - Darazo
                        - Dass
                        - Gamawa
                        - Ganjuwa
                        - Giade
                        - Itas/Gadau
                        - Jama'Are
                        - Katagum
                        - Kirfi
                        - Misau
                        - Ningi
                        - Shira
                        - Tafawa-Balewa
                        - Toro
                        - Warji
                        - Zaki
                        - Ado
                        - Agatu
                        - Apa
                        - Buruku
                        - Gboko
                        - Guma
                        - Gwer-East
                        - Gwer-West
                        - Katsina-Ala
                        - Konshisha
                        - Kwande
                        - Logo
                        - Makurdi
                        - Ogbadibo
                        - Ohimini
                        - Oju
                        - Okpokwu
                        - Otukpo
                        - Oturkpa
                        - Tarka
                        - Ukum
                        - Vandekya
                        - Abadan
                        - Askira-Uba
                        - Bama
                        - Bayo
                        - Biu
                        - Chibok
                        - Damboa
                        - Dikwa
                        - Gubio
                        - Guzamala
                        - Gwoza
                        - Hawul
                        - Jere
                        - Kaga
                        - Kala/Balge
                        - Konduga
                        - Kukawa
                        - Kwaya-Kusar
                        - Mafa
                        - Magumeri
                        - Maiduguri
                        - Marte
                        - Mobbar
                        - Mongunu
                        - Ngala
                        - Nganzai
                        - Shani
                        - Adagbabiri
                        - Brass
                        - Ekeremor
                        - Kembe
                        - Kolokuma
                        - Kolokuma/Opkuma
                        - Nembe
                        - Ogbia
                        - Sagbama
                        - Southern-Ijaw
                        - Toru-Abubo
                        - Yenegoa
                        - Abi
                        - Abuochichie
                        - Akamkpa
                        - Akpabuyo
                        - Bakassi
                        - Bekwara
                        - Biasi
                        - Boki
                        - Calabar-Municipal
                        - Calabar-South
                        - Etunk
                        - Ikom
                        - Obanliku
                        - Obubra
                        - Obudu
                        - Odukpani
                        - Ogoja
                        - Ugep-North
                        - Yakurr
                        - Yala
                        - Aniocha North
                        - Aniocha-North
                        - Aniocha-South
                        - Bomadi
                        - Burutu
                        - Effurun
                        - Ethiope-East
                        - Ethiope-West
                        - Idu
                        - Ika-Ne
                        - Ika-North-East
                        - Ika-South
                        - Ikpemili
                        - Isoko-North
                        - Isoko-South
                        - Ndokwa-East
                        - Ndokwa-North
                        - Ndokwa-South
                        - Ndokwa-West
                        - Okpe
                        - Okwuani
                        - Oleh
                        - Oshielli-North
                        - Oshimili
                        - Oshimili-North
                        - Oshimili-South
                        - Osimili
                        - Osimili-North
                        - Osimili-South
                        - Patani
                        - Sapele
                        - Udokwa
                        - Udu
                        - Ughelli-North
                        - Ughelli-South
                        - Ukwuani
                        - Uraun
                        - Urwie
                        - Uvie
                        - Uvwei
                        - Uvwie
                        - Uwvie
                        - Warri-Central
                        - Warri-North
                        - Warri-South
                        - Abakaliki
                        - Afikpo-North
                        - Afikpo-South
                        - Bomadim
                        - Ebonyi
                        - Ezza-North
                        - Ezza-South
                        - Ikwo
                        - Ishielu
                        - Ivo
                        - Izzi
                        - Obaukwu
                        - Ohakwu
                        - Onicha
                        - Ukaba
                        - Afokpella
                        - Afuze
                        - Agbazilo
                        - Akoko Edo
                        - Akoko-Edo
                        - Egor
                        - Esan-Central
                        - Esan-North-East
                        - Esan-South-East
                        - Esan-West
                        - Etsako-Central
                        - Etsako-East
                        - Etsako-West
                        - Igueben
                        - Iguobano North East
                        - Ikpoba-Okha
                        - Ohunmwode
                        - Ologbo
                        - Opoji Irrua
                        - Oredo
                        - Orhionmwon
                        - Ovia-North-East
                        - Ovia-South-West
                        - Owan East
                        - Owan-East
                        - Owan-West
                        - Uhunmwonde
                        - Ado-Ekiti
                        - Aiyekire
                        - Efon
                        - Ekiti-East
                        - Ekiti-South-West
                        - Ekiti-West
                        - Emure/Ise/Orun
                        - Gbonyin
                        - Ido-Osi
                        - Ijero
                        - Ikare
                        - Ikere
                        - Ikole
                        - Ilejemeje
                        - Irepodun/Ifelodun
                        - Ise-Orun
                        - Moba
                        - Oye
                        - Aninri
                        - Awgu
                        - Enugu-East
                        - Enugu-North
                        - Enugu-South
                        - Ezeagu
                        - Igbo-Etiti
                        - Igbo-Eze-North
                        - Igbo-Eze-South
                        - Isi-Uzo
                        - Nkanu-East
                        - Nkanu-West
                        - Nsukka
                        - Nukanu East
                        - Oji-River
                        - Udenu
                        - Udi
                        - Uzo-Uwani
                        - Abaji
                        - Abuja Municipal
                        - Gwagwalada
                        - Kuje
                        - Bwari
                        - Kwali
                        - Akko
                        - Balanga
                        - Billiri
                        - Dukku
                        - Funakaye
                        - Gombe
                        - Kaltungo
                        - Kwami
                        - Nafada/Bajoga
                        - Shomgom
                        - Yamaltu/Deba
                        - Aboh-Mbaise
                        - Ahiazu-Mbaise
                        - Dral-Esat
                        - Ehime-Mbano
                        - Ezeobodo
                        - Ezinihitte
                        - Ideato
                        - Ideato-North
                        - Ideato-South
                        - Ihitte/Uboma
                        - Ikeduru
                        - Isiala-Mbano
                        - Isu
                        - Mbaitoli
                        - Mbano
                        - Ngor-Okpala
                        - Njaba
                        - Nkwerre
                        - Nwangele
                        - Obowo
                        - Oguta
                        - Ohaji-Egbema
                        - Okigwe
                        - Onuimo
                        - Orlu
                        - Oro-West
                        - Orsu
                        - Oru-East
                        - Oru-West
                        - Owerri-Municipal
                        - Owerri-North
                        - Owerri-West
                        - Ugiri-Ike Ikeduru
                        - Ugiri-Ikedikeduru
                        - Unbano
                        - Zinihitte
                        - Auyo
                        - Babura
                        - Biriniwa
                        - Birnin-Kudu
                        - Bosuwa
                        - Buji
                        - Dutse
                        - Gagarawa
                        - Garki
                        - Gumel
                        - Guri
                        - Gwaram
                        - Gwiwa
                        - Hadejia
                        - Jahun
                        - Kafin-Hausa
                        - Kaugama
                        - Kazaure
                        - Kirkasamma
                        - Maigatari
                        - Malam-Maduri
                        - Miga
                        - Ringim
                        - Roni
                        - Sule-Tankarkar
                        - Taura
                        - Yankwashi
                        - Aleiro
                        - Arewa-Dandi
                        - Argungu
                        - Augie
                        - Bagudo
                        - Birnin-Kebbi
                        - Bumza
                        - Dandi
                        - Danko
                        - Fakai
                        - Gwandu
                        - Jega
                        - Kalgo
                        - Koko-Besse
                        - Maiyama
                        - Ngaski
                        - Sakaba
                        - Shanga
                        - Suru
                        - Wasagu
                        - Yauri
                        - Zuru
                        - Birnin-Gwari
                        - Chikun
                        - Giwa
                        - Gwagwada
                        - Igabi
                        - Ikara
                        - Jaba
                        - Jema'A
                        - Kachia
                        - Kaduna-North
                        - Kagarko
                        - Kajuru
                        - Kaura
                        - Kauru
                        - Koka/Kawo
                        - Kubah
                        - Kudan
                        - Lere
                        - Makarfi
                        - Sabon-Gari
                        - Sanga
                        - Soba
                        - Tudun-Wada/Makera
                        - Zango-Kataf
                        - Zaria
                        - Ajingi
                        - Albasu
                        - Bagwai
                        - Bebeji
                        - Bichi
                        - Bunkure
                        - Dala
                        - Dambatta
                        - Dawakin-Kudu
                        - Dawakin-Tofa
                        - Doguwa
                        - Fagge
                        - Gabasawa
                        - Garko
                        - Garun-Mallam
                        - Gaya
                        - Gezawa
                        - Gwale
                        - Gwarzo
                        - Kano-Municipal
                        - Karaye
                        - Kibiya
                        - Kiru
                        - Kumbotso
                        - Kunchi
                        - Kura
                        - Madobi
                        - Makoda
                        - Minjibir
                        - Nasarawa
                        - Rano
                        - Rimin-Gado
                        - Rogo
                        - Shanono
                        - Sumaila
                        - Takai
                        - Tarauni
                        - Tofa
                        - Tsanyawa
                        - Tudun-Wada
                        - Ungogo
                        - Warawa
                        - Wudil
                        - Adavi
                        - Ajaokuta
                        - Ankpa
                        - Dekina
                        - Ibaji
                        - Idah
                        - Igalamela
                        - Ijumu
                        - Ikoyi-Ijumu
                        - Kabba/Bunu
                        - Kogi
                        - Lokoja
                        - Mopa-Muro-Mopi
                        - Obaji
                        - Ofu
                        - Ogori/Magongo
                        - Okehi
                        - Okene
                        - Olamaboro
                        - Omala
                        - Oru
                        - Oyi
                        - Yagba-East
                        - Yagba-West
                        - Bakori
                        - Batagarawa
                        - Batsari
                        - Baure
                        - Bindawa
                        - Charanchi
                        - Dan-Musa
                        - Dandume
                        - Danji
                        - Daura
                        - Dutsi
                        - Dutsinma
                        - Faskari
                        - Funtua
                        - Ingawa
                        - Jibia
                        - Kafur
                        - Kaita
                        - Kankara
                        - Kankia
                        - Katsina
                        - Kurfi
                        - Kusada
                        - Mai-Adua
                        - Malumfashi
                        - Mani
                        - Mashi
                        - Matazu
                        - Musawa
                        - Rimi
                        - Sabuwa
                        - Safana
                        - Sandamu
                        - Zango
                        - Asa
                        - Baruten
                        - Edu
                        - Ekiti
                        - Ifelodun
                        - Ilorin south
                        - Ilorin west
                        - Ilorin east
                        - Irepodun
                        - Isin
                        - Kaiama
                        - Moro
                        - Offa
                        - Oke ero
                        - Oyun
                        - Pategi
                        - Agege
                        - Ajeromi-Ifelodun
                        - Alimosho
                        - Amuwo-Odofin
                        - Apapa
                        - Badagry
                        - Epe
                        - Eti-Osa
                        - Ibeju-Lekki
                        - Ifako-Ijaiye
                        - Ikeja
                        - Ikorodu
                        - Kosofe
                        - Lagos-Island
                        - Lagos-Mainland
                        - Mushin
                        - Ojo
                        - Oshodi-Isolo
                        - Shomolu
                        - Somolu
                        - Surulere
                        - Akwanga
                        - Awe
                        - Doma
                        - Karu
                        - Keana
                        - Keffi
                        - Kokona
                        - Lafia
                        - Nassawara
                        - Nassawara Eggon
                        - Obi
                        - Wambu
                        - Agaie
                        - Agwara
                        - Bida
                        - Borgu
                        - Bosso
                        - Chanchaga
                        - Edati
                        - Gbako
                        - Gurara
                        - Katcha
                        - Kontagora
                        - Lapai
                        - Lavun
                        - Magama
                        - Mariga
                        - Mashegu
                        - Mokwa
                        - Muya
                        - Paikoro
                        - Rafi
                        - Rijau
                        - Shiroro
                        - Suleja
                        - Tafa
                        - Wushishi
                        - Abeokuta-North
                        - Abeokuta-South
                        - Ado-Odo/Ota
                        - Ewekoro
                        - Ifo
                        - Ijebu-East
                        - Ijebu-North
                        - Ijebu-North-East
                        - Ijebu-Ode
                        - Ikenne
                        - Imeko-Afon
                        - Ipokia
                        - Obafemi-Owode
                        - Odeda
                        - Odogbolu
                        - Ogun-Waterside
                        - Remo-North
                        - Sagamu
                        - Yewa North
                        - Yewa South
                        - Akoko
                        - Akoko-North
                        - Akoko-North-West
                        - Akoko-South
                        - Akoko-South-East
                        - Akure
                        - Akure-North
                        - Akure-South
                        - Ese-Odo
                        - Idanre
                        - Ifedore
                        - Igbisin
                        - Ikale
                        - Ilaje
                        - Ilaje-West
                        - Ile-Oluji-Okeigbo
                        - Irele
                        - Odigbo
                        - Oka Ak0Ko
                        - Okiti Pupa Ijuodo
                        - Okiti-Pupa
                        - Ondo
                        - Ondo West
                        - Ondo-East
                        - Ose
                        - Owo
                        - Atakumosa
                        - Atakumosa East
                        - Ayeda-Ade
                        - Ayedire
                        - Boluwaduro
                        - Boripe
                        - Ede
                        - Ede North
                        - Egbedore
                        - Ejigbo
                        - Ife
                        - Ife North
                        - Ife South
                        - Ife-Central
                        - Ife-East
                        - Ila
                        - Ilesa-East
                        - Ilesa-West
                        - Ilesha
                        - Ilesha West
                        - Irewole
                        - Isokan
                        - Iwo
                        - Obokun
                        - Odo-Otin
                        - Ola Oluwa
                        - Olorunda
                        - Ori-Ade
                        - Orolu
                        - Osogbo
                        - Afijio
                        - Akinyele
                        - Atiba
                        - Atisbo
                        - Egbeda
                        - Ibadan-Central
                        - Ibadan-North-East
                        - Ibadan-North-West
                        - Ibadan-South-East
                        - Ibadan-South-West
                        - Ibarapa-Central
                        - Ibarapa-East
                        - Ibarapa-North
                        - Ido
                        - Irepo
                        - Iseyin
                        - Itseiwaju
                        - Iwajowa
                        - Kajola
                        - Lagelu
                        - Odo-Oluwa
                        - Ogbomosho-North
                        - Ogbomosho-South
                        - Olorunsogo
                        - Oluyole
                        - Ona-Ara
                        - Orelope
                        - Ori-Ire
                        - Oyo-East
                        - Oyo-West
                        - Saki-East
                        - Saki-West
                        - Barkin-Ladi
                        - Bassa
                        - Bokkos
                        - Jos-East
                        - Jos-North
                        - Jos-South
                        - Kanam
                        - Kanke
                        - Langtang-North
                        - Langtang-South
                        - Mangu
                        - Mikang
                        - Pankshin
                        - Quan'Anpan
                        - Riyom
                        - Shendam
                        - Wase
                        - Aboa/Odual
                        - Ahoada-East
                        - Ahoada-West
                        - Akukutoru
                        - Andoni
                        - Asari-Toru
                        - Bonny
                        - Buguma
                        - Degema
                        - Eleme
                        - Elfane
                        - Emuoha
                        - Etche
                        - Gokana
                        - Ikwerre
                        - Khana
                        - Obia/Akpor
                        - Ogba-Egbema-Ndoni
                        - Ogba/Egbema/Ndoni
                        - Ogu/Bolo
                        - Okirika
                        - Omuma
                        - Opobo/Nkoro
                        - Oyigbo
                        - Port-Harcourt
                        - Tai
                        - Binji
                        - Bodinga
                        - Dange-Shuni
                        - Gada
                        - Goronyo
                        - Gudu
                        - Gwadabawa
                        - Illela
                        - Kebbe
                        - Kware
                        - Raba
                        - Sabo-Birni
                        - Shagari
                        - Silame
                        - Sokoto-North
                        - Sokoto-South
                        - Tambuwal
                        - Tangaza
                        - Tureta
                        - Wamakko
                        - Wurno
                        - Yabo
                        - Ardo-Kola
                        - Bali
                        - Donga
                        - Gashaka
                        - Gassol
                        - Ibi
                        - Jalingo
                        - Karim-Lamido
                        - Kurmi
                        - Lau
                        - Oilingo
                        - Sardauna
                        - Takum
                        - Ussa
                        - Wukari
                        - Yorro
                        - Zing
                        - Bade
                        - Borsali
                        - Damaturu
                        - Fika
                        - Fune
                        - Geidam
                        - Gogaram
                        - Gujba
                        - Gulani
                        - Jakusko
                        - Karasuwa
                        - Machina
                        - Nangere
                        - Nguru
                        - Potiskum
                        - Tarmua
                        - Yunusari
                        - Yusufari
                        - Anka
                        - Bakura
                        - Bukkuyum
                        - Bungudu
                        - Gumi
                        - Gusau
                        - Isa
                        - Kaura-Namoda
                        - Kiyawa
                        - Maradun
                        - Maru
                        - Shinkafi
                        - Talata-Mafara
                        - Tsafe
                        - Zurmi
        '401':
          $ref: '#/components/responses/401-Response-for-API'
      security:
        - APIKey: []
  /api/v1/search:
    get:
      tags:
        - location
      summary: Search
      description: 'It allows developers to search for information about Nigeria based on the following categories; region, state and local government area(LGAs). It is possible if you want to search for a region with the states under them but not the local government. This also applies to states with LGAs. It returns the metadata for each search as well'
      operationId: get-api-v1-search?category=lga&query=Ikwuano
      parameters:
        - name: category
          in: query
          description: 'Defines the category to search in e.g Region, State or LGA'
          required: true
          schema:
            type: string
        - name: query
          in: query
          description: The name to search for in a category
          schema:
            type: string
      requestBody:
        content: {}
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      size:
                        type: integer
                      result:
                        type: array
                        items:
                          type: object
                          properties:
                            state:
                              type: string
                            lga:
                              type: string
                            metadata:
                              type: object
                              properties:
                                state:
                                  type: string
                                capital:
                                  type: string
                                slogan:
                                  type: string
                                senatorial_districts:
                                  type: array
                                  items:
                                    type: string
                                lgas:
                                  type: array
                                  items:
                                    type: string
                                landmass:
                                  type: string
                                population:
                                  type: string
                                dialect:
                                  type: string
                                map:
                                  type: string
                                latitude:
                                  type: string
                                longitude:
                                  type: string
                                website:
                                  type: string
                                geo_politcal_zone:
                                  type: string
                                created_date:
                                  type: string
                                created_by:
                                  type: string
                                past_governors:
                                  type: array
                                  items:
                                    type: string
                                borders:
                                  type: array
                                  items:
                                    type: string
                                known_for:
                                  type: array
                                  items:
                                    type: string
              examples:
                Example 1:
                  value:
                    success: true
                    message: Search results
                    data:
                      size: 1
                      result:
                        - state: Abia
                          lga: Ikwuano
                          metadata:
                            state: Abia
                            capital: Umuahia
                            slogan: God's Own State
                            senatorial_districts:
                              - Abia Central
                              - Abia North
                              - Abia South
                            lgas:
                              - Aba North
                              - Aba South
                              - Arochukwu
                              - Bende
                              - Isuikwuato
                              - Osisioma-Ngwa
                              - Obioma-Ngwa
                              - Ohafia
                              - Ikwuano
                              - Umu-Nneochi
                              - Isiala Ngwa South
                              - Isiala Ngwa North
                              - Ugwunagbo
                              - Ukwa West
                              - Ukwa East
                              - Umuahia South
                              - Umuahia North
                            landmass: '6,320 km2 (2,440 sq mi)'
                            population: '2,833,999'
                            dialect: Igbo
                            map: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Nigeria_Abia_state_map.png/250px-Nigeria_Abia_state_map.png'
                            latitude: '5.524913'
                            longitude: '7.494296'
                            website: 'http://www.abiastate.gov.ng/'
                            geo_politcal_zone: South East
                            created_date: 27 August 1991
                            created_by: General Ibrahim Babangida
                            past_governors:
                              - Ogbonnaya Onu
                              - Chris Akomas
                              - Orji Uzor Kalu
                              - Theodore Orji
                              - Okezie Ikpeazu
                            borders:
                              - Akwa Ibom
                              - Cross River
                              - Ebonyi
                              - Enugu
                              - Imo
                              - Rivers
                            known_for:
                              - Enyimba International F.C.
                              - Abia Warriors F.C.
                              - 'Long Juju Slave Route, Arochukwu'
                              - Michael Okpara University of Agriculture
                              - National War Museum
                              - Azumini Blue River
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  errorCode:
                    type: integer
                  data:
                    type: object
              examples:
                Example 1:
                  value:
                    success: false
                    message: Invalid Search Category
                    errorCode: 400
                    data: {}
        '401':
          $ref: '#/components/responses/401-Response-for-API'
      security:
        - APIKey: []
tags:
  - name: auth
    description: Everything about authentication
  - name: location
    description: Access to Geographic data
components:
  securitySchemes:
    APIKey:
      type: apiKey
      description: It should contain the user's API key. Create a new account or regenerate key to get one
      name: X-Api-Key
      in: header
    LoginToken:
      type: http
      description: It should contain the token given to you when you log in.
      scheme: bearer
      bearerFormat: auth-scheme
  responses:
    401-Response-for-API:
      description: '401 Unauthorized Response: if API key is missing'
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
              message:
                type: string
              data:
                type: object
              errorCode:
                type: integer
          examples:
            Example 1:
              value:
                success: false
                message: API Key required in the Bearer Authorization! Sign up to get a key
                data: {}
                errorCode: 401
  schemas:
    User:
      type: object
      title: User
      description: The Model for Any User Created
      properties:
        username:
          type: string
          minLength: 3
          examples:
            - Jane
        password:
          type: string
          format: password
          minLength: 3
          examples:
            - janedoe
        email:
          type: string
          format: email
          examples:
            - janedoe@gmail.com
        APIKey:
          type: string
          examples:
            - $2b$10$fYxI13LEA4gh91ipJFbbo.5SIwZUJLS/y0LmJxEwpxPdkBr0mZdvq
      required:
        - username
        - password
      examples:
        - username: Janedoe
          email: jane@doe.com
          password: janedoe
security:
  - APIKey: []
